name: Run Fortune Teller

on:
  workflow_dispatch: # allows you to run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Compile Java program
        run: javac FortuneTeller.java
      - name: Run with sample input
        run: |
          printf "Tarun\nIs coolie movie good?\n" | java FortuneTeller

